chore($app):change the system architecture file
SurveyMoonBear/SurveyMoonbear_APP pull request #146
Opened 2023-10-24 14:58 UTC by taylor-wu96

description:
redraw the system architecture picture svg file in doc/architecture document

2023-10-26 22:52 UTC, soumyaray requested changes

2023-10-27 00:33 UTC, taylor-wu96 commented on doc/architecture/images/infrastructuredata-system_architecture.drawio.svg
Bigger things:
Redis: REDISCLOUD_VISUALREPORTS_URL In development we ran locally but in production, we ran on Heroku so how do we draw this diagram?
Sidekiq: yes we use it, but could give the first version and figure out the part?
@soumyaray  Can we draw a dashed (or light color) box around all the infrastructure that is running on Heroku? i think we could fix this in our meet time?

2023-10-27 00:38 UTC, soumyaray commented on doc/architecture/images/infrastructuredata-system_architecture.drawio.svg
yes let's discuss all these issues at our meeting today – it'll be good for the whole lab to understand these architectural issues.

2023-10-27 01:51 UTC, soumyaray commented on doc/architecture/images/infrastructuredata-system_architecture.drawio.svg
- [ ] Rename worker to 'Survey Response Store Worker'
- [ ] All external services and infrastructure (Google) can be empty fill

2023-10-30 12:03 UTC, soumyaray requested changes

2023-10-30 12:03 UTC, soumyaray commented on doc/architecture/images/infrastructuredata-system_architecture.drawio.svg
Oops, I forgot to mention that the Postgres DB server is on Heroku too – could you please include it in the Heroku box/shape?

2023-10-31 04:19 UTC, soumyaray requested changes

2023-10-31 04:19 UTC, soumyaray commented on doc/architecture/images/infrastructuredata-system_architecture.drawio.svg
please check that the arrowheads ending at Redis cloud machines can be clearly seen.

Also, consider just moving the Postgres Database to be between the Worker and Moonbear so that there isn't so much whitespace?

2023-11-02 02:22 UTC, taylor-wu96 commented on doc/architecture/images/infrastructuredata-system_architecture.drawio.svg
@soumyaray  I fix the issues

2023-11-02 02:29 UTC, soumyaray requested changes
Thanks -- looks much better!
Sorry but I keep finding small issues:
- The arrow should go from Web App to Rack Cache, not the other way around!  
- Also, rename to "Redis Rack Cache"?
- Arrow should be from Web browser to CDN (not other way around)
- There should be an arrowhead from browser to Web App.

Just to be clear, the arrows represents HTTP requests, so it should always go FROM what is requesting TO what is responding.

2023-11-02 07:45 UTC, taylor-wu96 commented
> Thanks -- looks much better! Sorry but I keep finding small issues:
> 
> * The arrow should go from Web App to Rack Cache, not the other way around!
> * Also, rename to "Redis Rack Cache"?
> * Arrow should be from Web browser to CDN (not other way around)
> * There should be an arrowhead from browser to Web App.
> 
> Just to be clear, the arrows represents HTTP requests, so it should always go FROM what is requesting TO what is responding.



> Thanks -- looks much better! Sorry but I keep finding small issues:
> 
> * The arrow should go from Web App to Rack Cache, not the other way around!
> * Also, rename to "Redis Rack Cache"?
> * Arrow should be from Web browser to CDN (not other way around)
> * There should be an arrowhead from browser to Web App.
> 
> Just to be clear, the arrows represents HTTP requests, so it should always go FROM what is requesting TO what is responding.

@soumyaray done~

2023-11-02 08:55 UTC, soumyaray approved these changes
great and thanks!

2023-11-02 08:56 UTC, soumyaray approved these changes
great and thanks!

2023-11-02 08:57 UTC, merged